version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY: "/devops/DockerRegistry"

phases:
  install:
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - echo "Pre-Build phase"
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - $(aws --region us-east-1 ecr get-login --registry-ids 639193537090 --no-include-email)
      - create_version_file.py --semantic_version 1.0
  build:
    commands:
      - echo "Build phase"
      - export GOPATH=$(pwd)
      - go get -t -d -v
      - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-s' -o go-mongo-backup
      - docker build -t ${IMAGE_NAME} .
      - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/$(cat git_branch)/${IMAGE_NAME}:$(cat composite_version)
      - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/$(cat git_branch)/${IMAGE_NAME}:latest
      - cd lambda/mongo-backup && zip -r ../../mongoBackup-$(cat ../../composite_version).zip . && cd ../..
  post_build:
    commands:
      - echo "Post-Build phase"
      - create_parameters.py --name ${IMAGE_NAME} --cluster ${CLUSTER_NAME}
      - zip -j deploy-${IMAGE_NAME}.zip git_branch composite_version specfiles/deploy-only/buildspec.yml
      - zip -j deploy-${IMAGE_NAME}.zip mongoBackup-$(cat composite_version).zip
      - zip -r deploy-${IMAGE_NAME}.zip cloudformation/${IMAGE_NAME}.yml infrastructure/pipeline.yml
      - docker push ${DOCKER_REGISTRY}/$(cat git_branch)/${IMAGE_NAME}:$(cat composite_version)
      - docker push ${DOCKER_REGISTRY}/$(cat git_branch)/${IMAGE_NAME}:latest
      - aws s3 cp mongoBackup-$(cat composite_version).zip s3://net-platform-devops-${ENV}/lambda/mongoBackup-$(cat composite_version).zip
      - |
        if [ "$(cat git_branch)" = "develop" ]; then
          aws s3 cp --acl bucket-owner-full-control deploy-${IMAGE_NAME}.zip s3://pipeline-artifacts-dev/deployment-packages/
          aws s3 cp --acl bucket-owner-full-control deploy-${IMAGE_NAME}.zip s3://pipeline-artifacts-ddev/deploy/
        fi
      - |
        if [ "$(cat git_branch)" = "master" ]; then
          aws s3 cp --acl bucket-owner-full-control deploy-${IMAGE_NAME}.zip s3://pipeline-artifacts-sit/deployment-packages/
          aws s3 cp --acl bucket-owner-full-control deploy-${IMAGE_NAME}.zip s3://pipeline-artifacts-dsit/deploy/
        fi
artifacts:
  files:
    - cloudformation/*
  discard-paths: yes
